spring.application.name=cyptowallet-backend
spring.data.mongodb.uri=mongodb+srv://devyadav8487_db_user:Tushar%400010@cluster0.sskkgq9.mongodb.net/walletDB?retryWrites=true&w=majority
server.port=8080

